version: "2.1"
services:
  unifi-app:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-app
    depends_on:
      - unifi-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MONGO_USER=MONGO_USER
      - MONGO_PASS=MONGO_PASS
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - ./config:/config
    networks:
      - unifi-network
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional

  unifi-db:
    image: mongo:4.4.24
    container_name: unifi-network-db
    networks:
      - unifi-network
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-data:/data/db
      - ./mongo-config:/data/configdb

networks:
  unifi-network:
    driver: bridge